export const initialState = {
  assessmentType: 'rubricval',
  categorySelected: '',
  competency: '',
  countAssetelement: 0,
  entityCheck: [
    { id: 1, value: 'SHRM', isChecked: false },
    { id: 2, value: 'AACSB', isChecked: false },
    { id: 3, value: 'ACBSP', isChecked: false },
    { id: 4, value: 'IACBE', isChecked: false },
    { id: 5, value: 'AMBA', isChecked: false },
    { id: 6, value: 'ACJS', isChecked: false },
    { id: 7, value: 'NASPAA', isChecked: false },
    { id: 8, value: 'CAEP', isChecked: false },
    { id: 9, value: 'CAHME', isChecked: false },
    { id: 10, value: 'AUPHA', isChecked: false },
    { id: 11, value: 'NACE', isChecked: false },
  ],
  componenetName: 'Add Assesment Items',
  entitySelect: 0,
  expstatement: [{ statement: '' }],
  expBehaviour: [{ behaviour: '' }],
  expstatementList: {},
  entityCheckedAll: false,
  fathSelected: '',
  itemsElements: [
    { statement: 'ali', behaviur: '', scaling: '' },
    { statement: '', behaviur: '', scaling: '' },
    { statement: '', behaviur: '', scaling: '' },
    { statement: '', behaviur: '', scaling: '' },
    { statement: '', behaviur: '', scaling: '' },
  ],
  lists: {},
  recommendAppCorporate: false,
  recommendAppHigher: false,
  typeSelected: 'influval',
  usage: '',
  validateArray: {},
};
