export enum lookups {
  assessmentTypesLookUp = 'assessmentTypesLookUp',
  billingPlansLookUp = 'billingPlansLookUp',
  categoriesLookUp = 'categoriesLookUp',
  competenciesLookUp = 'competenciesLookUp',
  emailTypesLookUp = 'emailTypesLookUp',
  entitiesLookUp = 'entitiesLookUp',
  evaluationRolesLookUp = 'evaluationRolesLookUp',
  questionTypesLookUp = 'questionTypesLookUp',
  instrumentStatusLookUp = 'instrumentStatusLookUp',
  recommendedApplicationsLookUp = 'recommendedApplicationsLookUp',
  statesLookUp = 'statesLookUp',
  countriesLookUp = 'countriesLookUp',
  testTypesLookUp = 'testTypesLookUp',
  userRolesLookUp = 'userRolesLookUp',
  clientTypesLookUp = 'clientTypesLookUp',
}
