import React from 'react';
import { RouteComponentProps, withRouter } from 'react-router-dom';
import IClientList from '../../../interfaces/Client';
import RouteParams from '../../../interfaces/RouteParams';
import EditComponent from '../AddClient';

const ClientData: IClientList[] = [
  {
    address: 'Cantt. MughalPura Lahore',
    billing: 'Biling 2',
    city: 'Lahore',
    clientInformation: 'Tkxel Client',
    clientName: 'TkXel',
    clientType: 'Educational institute',
    contact: [
      {
        id: '1',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
      {
        id: '2',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
      {
        id: '3',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
      {
        id: '4',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
    ],
    id: '1',
    noOfAssessments: '25',
    noOfEvaluators: '28',
    noOfParticipants: '30',
    phone: '+1 818-452-1505',
    plan: 'Plan 01',
    school: 'P.R Boys high school',
    state: 'punjab',
    status: 'inActive',
    userEmail: 'ali@tkxel.com',
    userFirstName: 'ali',
    userLastName: 'raza',
    zip: '54000',
  },
  {
    address: 'Cantt. MughalPura Lahore',
    billing: '',
    city: 'Lahore',
    clientInformation: '',
    clientName: 'TkXel',
    clientType: '',
    contact: [
      {
        id: '1',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
    ],
    id: '2',
    noOfAssessments: '25',
    noOfEvaluators: '28',
    noOfParticipants: '30',
    phone: '+1 818-452-1505',
    plan: 'Plan 01',
    school: 'P.R Boys high school',
    state: 'punjab',
    status: 'Active',
    userEmail: 'ali@tkxel.com',
    userFirstName: 'ali',
    userLastName: 'raza',
    zip: '54000',
  },
  {
    address: 'Cantt. MughalPura Lahore',
    billing: '',
    city: 'Lahore',
    clientInformation: '',
    clientName: 'TkXel',
    clientType: '',
    contact: [
      {
        id: '1',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
    ],
    id: '3',
    noOfAssessments: '25',
    noOfEvaluators: '28',
    noOfParticipants: '30',
    phone: '+1 818-452-1505',
    plan: 'Plan 01',
    school: 'P.R Boys high school',
    state: 'punjab',
    status: 'Active',
    userEmail: 'ali@tkxel.com',
    userFirstName: 'ali',
    userLastName: 'raza',
    zip: '54000',
  },
  {
    address: 'Cantt. MughalPura Lahore',
    billing: '',
    city: 'Lahore',
    clientInformation: '',
    clientName: 'TkXel',
    clientType: '',
    contact: [
      {
        id: '1',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
    ],
    id: '4',
    noOfAssessments: '25',
    noOfEvaluators: '28',
    noOfParticipants: '30',
    phone: '+1 818-452-1505',
    plan: 'Plan 01',
    school: 'P.R Boys high school',
    state: 'punjab',
    status: 'inActive',
    userEmail: 'ali@tkxel.com',
    userFirstName: 'ali',
    userLastName: 'raza',
    zip: '54000',
  },
  {
    address: 'Cantt. MughalPura Lahore',
    billing: '',
    city: 'Lahore',
    clientInformation: '',
    clientName: 'TkXel',
    clientType: '',
    contact: [
      {
        id: '1',
        email: 'maria@evaluskills.com',
        firstName: 'Maria',
        lastName: ' Garcia',
        phone: '+1 818-452-1505',
        role: '',
      },
    ],
    id: '5',
    noOfAssessments: '25',
    noOfEvaluators: '28',
    noOfParticipants: '30',
    phone: '+1 818-452-1505',
    plan: 'Plan 01',
    school: 'P.R Boys high school',
    state: 'punjab',
    status: 'Active',
    userEmail: 'ali@tkxel.com',
    userFirstName: 'ali',
    userLastName: 'raza',
    zip: '54000',
  },
];

const EditClient: React.FunctionComponent<RouteComponentProps<RouteParams>> = ({
  history,
  location,
  match,
}) => {
  const clientData: any = ClientData.find(client => client.id === match.params.id);
  return <EditComponent defaultValues={clientData} action="edit" />;
};

export default withRouter(EditClient);
